export type Language = 'fr' | 'en' | 'ar';

export const translations: Record<string, any> = {
    "fr": {
        "common": {
            "loading": "Chargement...",
            "save": "Sauvegarder",
            "cancel": "Annuler",
            "delete": "Supprimer",
            "edit": "Modifier",
            "close": "Fermer",
            "back": "Retour",
            "next": "Suivant",
            "finish": "Terminer",
            "error": "Une erreur est survenue",
            "success": "Succès",
            "search": "Rechercher...",
            "filter": "Filtrer",
            "autoGenerated": "Auto-généré",
            "date": "Date",
            "exportPDF": "Exporter en PDF",
            "exporting": "Exportation..."
        },
        "auth": {
            "login": "Connexion",
            "register": "Inscription",
            "logout": "Déconnexion",
            "guest": "Continuer en invité",
            "joinElite": "Rejoins l'Élite",
            "championReturn": "Le retour du Champion",
            "claimThrone": "Récupère ton Trône",
            "identityVerif": "Vérification d'Identité",
            "accessAuthorized": "Accès Autorisé",
            "pseudoOrEmail": "Pseudo ou Email",
            "pseudo": "Ton Pseudo",
            "email": "E-mail Personnel",
            "password": "Mot de Passe",
            "newPassword": "Nouveau Mot de Passe (Min. 6)",
            "gender": "Genre",
            "ageRange": "Tranche d'Âge",
            "age1518": "15-18 ans",
            "age1923": "19-23 ans",
            "age24plus": "24+ ans",
            "acceptPolicy": "J'accepte les politiques de confidentialité de LEVELMAK",
            "forgot": "Perdu ?",
            "backToLogin": "Retour à la connexion",
            "backToPrev": "Retour à l'étape précédente",
            "verifyIdentity": "Vérifier Identité",
            "changeAccess": "Changer l'accès",
            "verifying": "Vérification...",
            "requestValidated": "Demande validée !",
            "updatingAccess": "TMAB GROUP met à jour ton accès Élite...",
            "errorSystem": "SYSTÈME : ERREUR",
            "orVia": "Ou via",
            "googleAuth": "Authentification Google",
            "biometricAuth": "Connexion Biométrique",
            "accessDashboard": "Accéder au Dashboard",
            "continue": "Continuer",
            "propelKnowledge": "Propulser mon Savoir",
            "legal": "Protection des données conforme • Accès sécurisé SSL",
            "placeholderPseudo": "Ex: mouctar1234",
            "placeholderEmail": "Ex: mail@ecole.com"
        },
        "nav": {
            "dashboard": "Tableau de bord",
            "quiz": "Quiz IA",
            "summary": "Résumé IA",
            "library": "Bibliothèque",
            "writing": "Atelier Écriture",
            "flashcards": "Flashcards",
            "ranking": "Classement",
            "shop": "Boutique",
            "planner": "Planif IA",
            "social": "Communauté",
            "settings": "Paramètres"
        },
        "settings": {
            "title": "Paramètres",
            "subtitle": "Système",
            "desc": "Personnalise ton expérience LEVELMAK et gère tes informations personnelles.",
            "panel": "Panneau de Contrôle",
            "profile": "Profil & Identité",
            "appearance": "Apparence",
            "notifications": "Notifications",
            "security": "Sécurité",
            "photoTitle": "Photo de Profil",
            "photoDesc": "Format JPG, PNG ou GIF. Max 5Mo.",
            "fullName": "Nom Complet",
            "phoneNum": "Numéro de Téléphone",
            "saveBtn": "Enregistrer les modifications",
            "saving": "Enregistrement...",
            "success": "Modifications enregistrées !",
            "darkMode": "Mode Sombre",
            "darkOn": "Activé par défaut",
            "lightOn": "Mode clair activé",
            "appSounds": "Sons de l'App",
            "soundsOn": "Activer les effets",
            "soundsOff": "Sons désactivés",
            "fontSize": "Taille de Police",
            "fontSizeDesc": "Ajuste la taille du texte pour ton confort.",
            "lang": "Langue",
            "currentLang": "Français (France)",
            "version": "Version",
            "build": "v2.4.0",
            "notifTitle": "Préférences de Notifications",
            "notifDesc": "Choisis comment tu souhaites rester informé.",
            "notifMissions": "Rappels de Missions",
            "notifQuiz": "Nouveaux Quiz IA",
            "notifCommunity": "Alertes Communauté",
            "securityTitle": "Protection du Compte",
            "securityDesc": "Gère la sécurité de ton accès élite.",
            "changePw": "Changer le mot de passe",
            "oldPw": "Ancien mot de passe",
            "newPw": "Nouveau mot de passe",
            "sessions": "Sessions Actives",
            "sessionsDesc": "Tu es connecté sur cet appareil (App Mobile)."
        },
        "layout": {
            "important": "IMPORTANT",
            "welcome": "Bonjour,",
            "ready": "Prêt pour une session ?",
            "me": "Moi",
            "infoAvatarTitle": "Avatar & Identité",
            "infoAvatarQ": "📸 Comment changer de photo ?",
            "infoAvatarDesc": "Sur LEVELMAK, ta photo de profil est ton grade. Tu ne peux pas télécharger d'image externe : pour être respecté dans le classement, tu dois **acheter tes avatars dans la boutique** avec tes Coins. Plus ton avatar est rare, plus ton statut d'Elite est incontestable !",
            "infoRulesTitle": "Les Règles d'Or",
            "infoRule1": "Respect Mutuel : La communauté est basée sur l'entraide.",
            "infoRule2": "Intégrité : Gagnez vos XP sans tricher pour réellement progresser.",
            "infoRule3": "Confidentialité : Vos données sont protégées par TMAB GROUP.",
            "infoQualityTitle": "Engagement Qualité TMAB GROUP",
            "infoQualityDesc": "Nous nous engageons à lutter pour que LEVELMAK reste l'outil le plus accessible, puissant et innovant pour la jeunesse africaine et mondiale. L'avenir appartient à ceux qui apprennent.",
            "infoGotIt": "J'ai compris, c'est parti !",
            "bubblePatience": "Patience... 🧘‍♂️",
            "bubblePatienceDesc": "Encore {min} minutes de travail pour débloquer le Lâcher-Prise.",
            "installIosTitle": "Installer sur iPhone",
            "installIosDesc": "Ajoute LEVELMAK à ton écran d'accueil pour une expérience optimale et un accès rapide.",
            "installIosStep1": "Clique sur le bouton **Partager** en bas de Safari.",
            "installIosStep2": "Fais défiler et appuie sur **Sur l'écran d'accueil**.",
            "installIosStep3": "Clique sur **Ajouter** en haut à droite.",
            "installIosGotIt": "C'est compris !",
            "installApp": "Installer l'App",
            "installBtn": "Installer l'App",
            "elitePortal": "Portail Elite",
            "eliteStudent": "Étudiant Pro",
            "logout": "Se déconnecter"
        },
        "dashboard": {
            "online": "En ligne",
            "offline": "Hors-ligne",
            "time": {
                "min": "min",
                "hoursShort": "h",
                "minShort": "m"
            },
            "stats": {
                "xp": "Total XP",
                "quiz": "Quiz Faits",
                "time": "Temps d'étude",
                "badges": "Badges"
            },
            "profile": {
                "level": "Niveau",
                "studentPro": "Étudiant PRO",
                "eliteMember": "Membre Élite",
                "nextLevel": "Tu es à",
                "ofNextLevel": "du prochain niveau",
                "remaining": "restants"
            },
            "dice": {
                "chance": "Chance Quotidienne",
                "title": "Le Dé de la Chance",
                "subtitle": "Clique pour tenter ta chance ! 🎁✨",
                "rolling": "Lancer...",
                "won": "Gagné",
                "item": "Accessoire Ultra-Rare !",
                "itemDesc": "Vérifie ton inventaire dans la boutique !",
                "joker": "Joker Gagné !",
                "jokerDesc": "Tu as reçu une Fiole de Sauvetage !",
                "jackpot": "JACKPOT !!!",
                "preparing": "Le coach prépare la surprise...",
                "modalTitle": "Dé de la Chance",
                "modalSubtitle": "Lance le dé et découvre ta récompense !",
                "spin": "Lancer le dé",
                "itemWon": "Accessoire Ultra-Rare !",
                "checkInventory": "Vérifie ton inventaire dans la boutique !",
                "jokerWon": "Joker Gagné !",
                "jokerMsg": "Tu as reçu une Fiole de Sauvetage !",
                "coachPreparing": "Le coach prépare la surprise...",
                "accessory": "Accessoire"
            },
            "motivation": {
                "title": "L'Esprit du Jour",
                "loading": "Inspiration en cours...",
                "author": "Coach IA"
            },
            "vocab": {
                "title": "Découverte du Jour",
                "subtitle": "Enrichis ton vocabulaire",
                "example": "Exemple"
            },
            "activity": {
                "title": "Activité Récente",
                "viewAll": "Voir Tout",
                "reduce": "Réduire",
                "empty": "Pas d'activité."
            },
            "missions": {
                "title": "Objectifs",
                "empty": "Tous les objectifs sont complétés ! 🎉"
            },
            "ranking": {
                "title": "Classement",
                "button": "Classement Global"
            },
            "footer": {
                "property": "PROPRIÉTÉ EXCLUSIVE DE"
            },
            "srs": {
                "title": "À Réviser",
                "items": "éléments dus",
                "cardsDue": "cartes à revoir"
            }
        },
        "creativeWriting": {
            "title": "Écris ton Histoire",
            "tag": "Espace Créatif",
            "newDraft": "Nouvel écrit",
            "tabs": {
                "write": "Écrire",
                "myStories": "Mes écrits",
                "discover": "Découvrir"
            },
            "categories": {
                "story": "Histoire",
                "poem": "Poème",
                "column": "Chronique",
                "essay": "Essai",
                "other": "Autre"
            },
            "form": {
                "titleLabel": "Titre de l'œuvre",
                "titlePlaceholder": "Ex: Le mystère du Baobab géant...",
                "contentLabel": "Ton texte",
                "contentPlaceholder": "Il était une fois dans un village lointain...",
                "characters": "car.",
                "public": "Public",
                "saveBtn": "Sauvegarder",
                "saving": "Enregistrement...",
                "documentSettings": "Config. du Document"
            },
            "coach": {
                "title": "Coach IA",
                "subtitle": "Inspiration & Analyse",
                "reviewBtn": "Avis",
                "helpBtn": "M'aider",
                "potion": "Essence d'Inspiration",
                "empty": "Clique sur \"M'aider\" pour que j'écrive la suite, ou sur \"Avis\" pour mon analyse.",
                "analysis": "Analyse du Coach",
                "suggestion": "Suggestion créative",
                "insert": "Insérer dans le texte",
                "errorQuota": "Oups ! Le coach est un peu fatigué (quota atteint). Réessaie dans une minute !",
                "errorGeneral": "Le coach a eu un petit problème. Réessaie encore."
            },
            "list": {
                "empty": "Écris ton premier chef-d'œuvre",
                "startBtn": "Démarrer l'écriture",
                "deleteConfirm": "Es-tu sûr de vouloir supprimer cette œuvre ?",
                "modified": "Modifier",
                "by": "Par"
            },
            "writingLab": {
                "title": "Assistant Labo d'Écriture",
                "analyzeBtn": "Lancer l'Analyse Premium",
                "analyzing": "Analyse en cours...",
                "score": "Score de rédaction",
                "criteria": {
                    "style": "Style & Fluidité",
                    "grammar": "Grammaire & Orthographe",
                    "vocabulary": "Richesse Lexicale",
                    "structure": "Structure & Rythme"
                },
                "corrections": "Améliorations suggérées",
                "synonyms": "Synonymes & Élégance",
                "getSynonyms": "Enrichir le vocabulaire",
                "apply": "Appliquer",
                "empty": "Rédige au moins 50 caractères pour lancer l'analyse pédagogique.",
                "strength": "Force du texte"
            }
        },
        "library": {
            "title": "Bibliothèque IA",
            "subtitle": "Savoir Illimité",
            "desc": "Accède à des millions de ressources pédagogiques.",
            "searchPlaceholder": "Sujet, auteur, livre, question...",
            "searchBtn": "Explorer",
            "searching": "Recherche...",
            "analyzing": "Analyse Intelligente",
            "freeBooks": "Livres Gratuits (livre21.com)",
            "localBooks": "Ma Collection Locale",
            "privateCollection": "Ma Collection Privée",
            "hide": "Masquer",
            "download": "Télécharger",
            "open": "Ouvrir",
            "read": "Lire",
            "readOnline": "Lire en ligne",
            "downloadKeep": "Télécharger & Garder",
            "keep": "Garder",
            "startRead": "Lire maintenant",
            "summarize": "Résumer",
            "flashcards": "Flashcards",
            "quiz": "Quiz IA",
            "deleteConfirm": "Supprimer ce livre ?",
            "summaryTitle": "Résumé IA",
            "keyPoints": "Ce qu'il faut retenir",
            "readingTime": "Lecture",
            "difficulty": "Difficulté",
            "glossary": "Glossaire",
            "createQuiz": "Créer un Quiz",
            "createFlashcards": "Flashcards",
            "loadingSummary": "Gemini synthétise le savoir...",
            "readerTitle": "Lecteur Intégré LEVELMAK",
            "clear": "Effacer",
            "reco": "Reco IA",
            "sources": "Sources d'Accès Libre (Humanitaire)",
            "emptySearch": "Aucun résultat trouvé.",
            "geminiSearch": "Gemini explore les bases de données...",
            "geminiAnalyze": "Analyse des ressources pédagogiques..."
        },
        "shop": {
            "title": "Boutique LEVELMAK",
            "subtitle": "Équipe ton Avatar",
            "desc": "Dépense tes LevelCoins durement gagnés pour personnaliser ton profil et afficher tes succès à toute la communauté.",
            "balance": "Balance",
            "items": "Items",
            "tabs": {
                "all": "Tout",
                "avatar": "Avatars",
                "badge": "Badges",
                "theme": "Thèmes",
                "potion": "Fioles"
            },
            "success": "Achat réussi : ",
            "owned": "Possédé",
            "stock": "Stock",
            "active": "Actif",
            "equip": "Équiper",
            "buy": "Acheter",
            "use": "Utiliser",
            "empty": "Aucun item trouvé dans cette catégorie.",
            "insufficient": "Pas assez de LevelCoins ! 🪙"
        },
        "items": {
            "potion_double_xp": {
                "name": "Potion de Double XP",
                "desc": "Double tes gains d'XP pendant 5 minutes."
            },
            "potion_shield": {
                "name": "Bouclier de Quiz",
                "desc": "Pardonne une mauvaise réponse lors d'un quiz."
            },
            "potion_skip": {
                "name": "Fiole de Sauvetage",
                "desc": "Permet de passer une question de quiz sans répondre."
            },
            "potion_inspiration": {
                "name": "Essence d'Inspiration",
                "desc": "Donne une idée de roman unique via l'IA."
            },
            "potion_mystery": {
                "name": "Fiole Mystère",
                "desc": "Débloque un avatar au hasard dans la boutique."
            },
            "potion_fortune": {
                "name": "Élixir de Fortune",
                "desc": "Augmente les gains de LevelCoins pendant 10 minutes."
            },
            "badge_elite": {
                "name": "Badge Élite",
                "desc": "Affiche ton statut d'étudiant exceptionnel."
            },
            "badge_master": {
                "name": "Maître des Quiz",
                "desc": "Pour ceux qui ne ratent jamais une question."
            },
            "theme_gold": {
                "name": "Thème Or Royal",
                "desc": "Une interface luxueuse pour ton dashboard."
            },
            "theme_neon": {
                "name": "Thème Néon Cyber",
                "desc": "Un look futuriste et dynamique."
            }
        },
        "quiz": {
            "generator": {
                "title": "Générateur",
                "subtitle": "Ultra-Intelligent",
                "desc": "Transforme tes cours (Photos, PDF, Word) en expériences d'apprentissage",
                "active": "actives",
                "badge": "IA Pédagogique Avancée",
                "uploadBtn": "Documents",
                "textBtn": "Saisir Texte",
                "placeholder": "Colle ici ton cours...",
                "uploadDesc": "Combine tes photos de cahiers, PDF ou fichiers Word.",
                "generateBtn": "Propulser le Quiz",
                "intensity": "Intensité",
                "difficulties": {
                    "easy": "Facile",
                    "medium": "Intermédiaire",
                    "hard": "Expert"
                },
                "errors": {
                    "noFile": "Ajoute au moins un document ou une photo !",
                    "noText": "Saisis du texte pour générer le quiz !"
                },
                "status": {
                    "init": "Initialisation...",
                    "prep": "Préparation des documents...",
                    "read": "Lecture de",
                    "process": "Traitement de",
                    "analyze": "Analyse pédagogique par l'IA...",
                    "ready": "Quiz prêt ! Redirection..."
                }
            },
            "player": {
                "oracle": {
                    "title": "L'Oracle des Prédictions",
                    "subtitle": "Pari sur ta performance pour tripler tes pièces !",
                    "betAmount": "Combien paries-tu ?",
                    "betTarget": "Ton objectif de score ?",
                    "startBtn": "Commencer le Quiz",
                    "none": "Aucun"
                },
                "potions": {
                    "shield": "Activer le Bouclier",
                    "skip": "Utiliser Sauvetage"
                },
                "feedback": {
                    "success": [
                        "Génial !",
                        "Bravo !",
                        "Tu es un génie !",
                        "Quelle maîtrise !",
                        "Exactement !"
                    ],
                    "shield": "Bouclier activé ! Ton erreur est pardonnée. Réessaie ! 🛡️",
                    "fail": "Pas loin ! Apprends de cette erreur.",
                    "skip": "Fiole de Sauvetage utilisée ! Passage à la question suivante. ✨"
                },
                "results": {
                    "title": "Exploit Scolaire Accomplie !",
                    "completed": "Tu as terminé :",
                    "score": "Score Final",
                    "precision": "Précision",
                    "xp": "XP Gagnés",
                    "time": "Temps",
                    "betWin": "Prédiction Validée !",
                    "betFail": "Prédiction Échouée",
                    "betWinMsg": "Félicitations ! Tu as gagné",
                    "betFailMsg": "Dommage ! L'objectif de",
                    "summary": "Résumé du Cours",
                    "summarySub": "Synthèse intelligente générée par IA",
                    "keyPoints": "Points Clés",
                    "lexicon": "Lexique Technique",
                    "retryBtn": "Refaire le Quiz",
                    "downloadBtn": "Télécharger la Fiche (PDF)",
                    "homeBtn": "Retour au Dashboard"
                }
            }
        },
        "ranking": {
            "title": "Classement Global",
            "subtitle": "L'élite de LEVELMAK en temps réel",
            "refresh": "Actualiser",
            "refreshing": "Actualisation...",
            "calculating": "Calcul des rangs mondiaux...",
            "allChallengers": "Tous les Challengers",
            "top50": "Top 50 Mondial",
            "me": "Moi",
            "level": "Niveau",
            "totalXp": "TOTAL XP",
            "noPlayers": "Aucun autre joueur trouvé.",
            "disclaimer": "Le classement est mis à jour toutes les 24 heures par TMAB GROUP. Continue tes quiz pour grimper dans le classement !"
        },
        "flashcards": {
            "memorization": "Mémorisation Rapide",
            "aiSubtitle": "L'IA transforme tes cours en cartes de mémorisation active pour apprendre 3x plus vite.",
            "searchPlaceholder": "Rechercher un deck...",
            "aiPrompt": "Qu'est-ce que tu veux mémoriser aujourd'hui ?",
            "subjectPlaceholder": "Sujet des flashcards...",
            "generate": "Générer",
            "myDecks": "Mes Decks",
            "cards": "cartes",
            "studiedYesterday": "Étudié hier",
            "neverStudied": "Jamais étudié",
            "launch": "Lancer",
            "deleteConfirm": "Voulez-vous vraiment supprimer ce deck de flashcards ?",
            "emptyState": "Aucun deck pour le moment. Utilise le générateur IA ci-dessus pour commencer !",
            "createdDeck": "Nouveau Deck Créé",
            "createdDeckDesc": "Un deck de {count} flashcards sur \"{title}\" a été généré."
        },
        "planner": {
            "strategic": "Planificateur Stratégique",
            "successScheduled": "Ton Succès Programmé",
            "subtitle": "Laisse l'IA organiser tes révisions de manière intelligente pour maximiser ta rétention et minimiser ton stress.",
            "examDate": "Date de l'examen",
            "subjectsToReview": "Matières à réviser",
            "subjectPlaceholder": "Ex: Maths, SVT...",
            "add": "Ajouter",
            "docsAndPhotos": "Documents & Photos (Optionnel)",
            "aiAnalysisDesc": "L'IA analysera tes vrais cours (Photos, PDF, Word) pour un programme sur mesure.",
            "generatePlan": "Générer mon plan",
            "generating": "Génération en cours...",
            "start": "Début",
            "end": "Fin",
            "topicsIdentified": "Sujets identifiés",
            "redoPlan": "Refaire un plan",
            "timeline": "Ma Timeline de Révision",
            "duration": "durée",
            "aiTips": "Conseils de l'IA",
            "focusTitle": "Focus & Productivité",
            "focusDesc": "Concentre-toi sur les matières où tu as le plus de difficultés le matin, quand ton cerveau est frais. 🧠⚡",
            "pomodoroTitle": "Technique Pomodoro",
            "pomodoroDesc": "Travaille par sessions de 25 minutes suivies de 5 minutes de pause pour maintenir une concentration maximale. ⏲️✅",
            "moreTips": "Plus de conseils",
            "errorQuota": "⏳ Quotas API atteints. Attends 1-2 minutes et réessaie !",
            "errorFail": "Échec de la génération. Réessaie encore !",
            "tooltip": {
                "fillDateAndSubject": "Remplis la date d'examen et ajoute au moins une matière",
                "selectDate": "Sélectionne une date d'examen",
                "addSubject": "Ajoute au moins une matière en cliquant sur +",
                "generatePlan": "Clique pour générer ton plan !"
            },
            "validation": {
                "selectDateAndSubject": "Sélectionne une date et au moins une matière !",
                "clickToAdd": "Clique sur le bouton + pour ajouter \"{title}\""
            }
        },
        "onboarding": {
            "welcome": "Bienvenue sur LEVELMAK",
            "start": "Commencer l'aventure",
            "skip": "Passer l'introduction",
            "next": "Suivant"
        },
        "levelBot": {
            "sessions": "Mes Discussions",
            "newChat": "Nouvelle Discussion",
            "deleteConfirm": "Supprimer cette discussion ?",
            "empty": "Aucune discussion active.",
            "back": "Retour au chat"
        }
    },
    "en": {
        "common": {
            "loading": "Loading...",
            "save": "Save",
            "cancel": "Cancel",
            "delete": "Delete",
            "edit": "Edit",
            "close": "Close",
            "back": "Back",
            "next": "Next",
            "finish": "Finish",
            "error": "An error occurred",
            "success": "Success",
            "search": "Search...",
            "filter": "Filter",
            "autoGenerated": "Auto-generated",
            "date": "Date",
            "exportPDF": "Export as PDF",
            "exporting": "Exporting..."
        },
        "auth": {
            "login": "Login",
            "register": "Register",
            "logout": "Logout",
            "guest": "Continue as Guest",
            "joinElite": "Join the Elite",
            "championReturn": "The Champion Returns",
            "claimThrone": "Claim Your Throne",
            "identityVerif": "Identity Verification",
            "accessAuthorized": "Access Authorized",
            "pseudoOrEmail": "Username or Email",
            "pseudo": "Your Username",
            "email": "Personal Email",
            "password": "Password",
            "newPassword": "New Password (Min. 6)",
            "gender": "Gender",
            "ageRange": "Age Range",
            "age1518": "15-18 years",
            "age1923": "19-23 years",
            "age24plus": "24+ years",
            "acceptPolicy": "I accept Levelmak's privacy policies",
            "forgot": "Lost?",
            "backToLogin": "Back to Login",
            "backToPrev": "Back to Previous Step",
            "verifyIdentity": "Verify Identity",
            "changeAccess": "Change Access",
            "verifying": "Verifying...",
            "requestValidated": "Request Validated!",
            "updatingAccess": "TMAB GROUP is updating your Elite access...",
            "errorSystem": "SYSTEM: ERROR",
            "orVia": "Or via",
            "googleAuth": "Google Authentication",
            "biometricAuth": "Biometric Login",
            "accessDashboard": "Access Dashboard",
            "continue": "Continue",
            "propelKnowledge": "Propel My Knowledge",
            "legal": "Data protection compliant • Secure SSL access",
            "placeholderPseudo": "Ex: hunter1234",
            "placeholderEmail": "Ex: mail@school.com"
        },
        "nav": {
            "dashboard": "Dashboard",
            "quiz": "AI Quiz",
            "summary": "AI Summary",
            "library": "Library",
            "writing": "Writing Lab",
            "flashcards": "Flashcards",
            "ranking": "Ranking",
            "shop": "Shop",
            "planner": "AI Planner",
            "social": "Community",
            "settings": "Settings",
            "ailab": "AI Lab",
            "feedback": "Feedback",
            "rating": "App Rating"
        },
        "settings": {
            "title": "Settings",
            "subtitle": "System",
            "desc": "Customize your LEVELMAK experience and manage your personal info.",
            "panel": "Control Panel",
            "profile": "Profile & Identity",
            "appearance": "Appearance",
            "notifications": "Notifications",
            "security": "Security",
            "photoTitle": "Profile Picture",
            "photoDesc": "JPG, PNG or GIF format. Max 5MB.",
            "fullName": "Full Name",
            "phoneNum": "Phone Number",
            "saveBtn": "Save changes",
            "saving": "Saving...",
            "success": "Changes saved!",
            "darkMode": "Dark Mode",
            "darkOn": "Active by default",
            "lightOn": "Light mode active",
            "appSounds": "App Sounds",
            "soundsOn": "Enable effects",
            "soundsOff": "Sounds disabled",
            "fontSize": "Font Size",
            "fontSizeDesc": "Adjust text size for your comfort.",
            "lang": "Language",
            "currentLang": "English (US)",
            "version": "Version",
            "build": "v2.4.0",
            "notifTitle": "Notification Preferences",
            "notifDesc": "Choose how you want to stay informed.",
            "notifMissions": "Mission Reminders",
            "notifQuiz": "New AI Quizzes",
            "notifCommunity": "Community Alerts",
            "securityTitle": "Account Protection",
            "securityDesc": "Manage your elite access security.",
            "changePw": "Change Password",
            "oldPw": "Old Password",
            "newPw": "New Password",
            "sessions": "Active Sessions",
            "sessionsDesc": "You are connected on this device (Mobile App)."
        },
        "layout": {
            "important": "IMPORTANT",
            "welcome": "Hello,",
            "ready": "Ready for a session?",
            "me": "Me",
            "infoAvatarTitle": "Avatar & Identity",
            "infoAvatarQ": "📸 How to change photo?",
            "infoAvatarDesc": "On LEVELMAK, your profile photo is your rank. You cannot upload an external image: to be respected in the ranking, you must **buy your avatars in the shop** with your Coins. The rarer your avatar, the more indisputable your Elite status!",
            "infoRulesTitle": "Golden Rules",
            "infoRule1": "Mutual Respect: The community is based on mutual aid.",
            "infoRule2": "Integrity: Earn your XP without cheating to truly progress.",
            "infoRule3": "Confidentiality: Your data is protected by TMAB GROUP.",
            "infoQualityTitle": "TMAB GROUP Quality Commitment",
            "infoQualityDesc": "We are committed to fighting so that LEVELMAK remains the most accessible, powerful, and innovative tool for African and global youth. The future belongs to those who learn.",
            "infoGotIt": "Got it, let's go!",
            "bubblePatience": "Patience... 🧘‍♂️",
            "bubblePatienceDesc": "{min} more minutes of work to unlock Letting Go.",
            "installIosTitle": "Install on iPhone",
            "installIosDesc": "Add LEVELMAK to your home screen for optimal experience and quick access.",
            "installIosStep1": "Click on the **Share** button at the bottom of Safari.",
            "installIosStep2": "Scroll down and press **Add to Home Screen**.",
            "installIosStep3": "Click on **Add** at the top right.",
            "installIosGotIt": "Got it!",
            "installApp": "Install App",
            "installBtn": "Install App",
            "elitePortal": "Elite Portal",
            "eliteStudent": "Pro Student",
            "logout": "Log Out"
        },
        "dashboard": {
            "online": "Online",
            "offline": "Offline",
            "time": {
                "min": "min",
                "hoursShort": "h",
                "minShort": "m"
            },
            "stats": {
                "xp": "Total XP",
                "quiz": "Quizzes Done",
                "time": "Study Time",
                "badges": "Badges"
            },
            "profile": {
                "level": "Level",
                "studentPro": "Student PRO",
                "eliteMember": "Elite Member",
                "nextLevel": "You are at",
                "ofNextLevel": "of next level",
                "remaining": "remaining"
            },
            "dice": {
                "chance": "Daily Luck",
                "title": "Lucky Dice",
                "subtitle": "Click to try your luck! 🎁✨",
                "rolling": "Rolling...",
                "won": "Won",
                "item": "Ultra-Rare Accessory!",
                "itemDesc": "Check your inventory in the shop!",
                "joker": "Joker Won!",
                "jokerDesc": "You received a Rescue Vial!",
                "jackpot": "JACKPOT !!!",
                "preparing": "Coach is preparing the surprise...",
                "modalTitle": "Lucky Dice",
                "modalSubtitle": "Roll the dice and discover your reward!",
                "spin": "Roll the dice",
                "itemWon": "Ultra-Rare Accessory!",
                "checkInventory": "Check your inventory in the shop!",
                "jokerWon": "Joker Won!",
                "jokerMsg": "You received a Rescue Vial!",
                "coachPreparing": "The coach is preparing the surprise...",
                "accessory": "Accessory"
            },
            "motivation": {
                "title": "Spirit of the Day",
                "loading": "Inspiration in progress...",
                "author": "AI Coach"
            },
            "vocab": {
                "title": "Daily Discovery",
                "subtitle": "Enrich your vocabulary",
                "example": "Example"
            },
            "activity": {
                "title": "Recent Activity",
                "viewAll": "View All",
                "reduce": "Collapse",
                "empty": "No activity."
            },
            "missions": {
                "title": "Goals",
                "empty": "All goals completed! 🎉"
            },
            "ranking": {
                "title": "Ranking",
                "button": "Global Ranking"
            },
            "footer": {
                "property": "EXCLUSIVE PROPERTY OF"
            },
            "srs": {
                "title": "To Review",
                "items": "items due",
                "cardsDue": "cards to review"
            }
        },
        "creativeWriting": {
            "title": "Write your Story",
            "tag": "Creative Space",
            "newDraft": "New Draft",
            "tabs": {
                "write": "Write",
                "myStories": "My Stories",
                "discover": "Discover"
            },
            "categories": {
                "story": "Story",
                "poem": "Poem",
                "column": "Column",
                "essay": "Essay",
                "other": "Other"
            },
            "form": {
                "titleLabel": "Title of the work",
                "titlePlaceholder": "Ex: The mystery of the giant Baobab...",
                "contentLabel": "Your text",
                "contentPlaceholder": "Once upon a time in a faraway village...",
                "characters": "chars.",
                "public": "Public",
                "saveBtn": "Save",
                "saving": "Saving...",
                "documentSettings": "Document Config."
            },
            "coach": {
                "title": "AI Coach",
                "subtitle": "Inspiration & Analysis",
                "reviewBtn": "Review",
                "helpBtn": "Help me",
                "potion": "Essence of Inspiration",
                "empty": "Click \"Help me\" for me to write the rest, or \"Review\" for my analysis.",
                "analysis": "Coach Analysis",
                "suggestion": "Creative Suggestion",
                "insert": "Insert into text",
                "errorQuota": "Oops! The coach is a bit tired (quota reached). Try again in a minute!",
                "errorGeneral": "The coach had a small problem. Try again."
            },
            "list": {
                "empty": "Write your first masterpiece",
                "startBtn": "Start writing",
                "deleteConfirm": "Are you sure you want to delete this work?",
                "modified": "Edit",
                "by": "By"
            },
            "writingLab": {
                "title": "Writing Lab Assistant",
                "analyzeBtn": "Launch Premium Analysis",
                "analyzing": "Analyzing...",
                "score": "Writing Score",
                "criteria": {
                    "style": "Style & Fluency",
                    "grammar": "Grammar & Spelling",
                    "vocabulary": "Lexical Richness",
                    "structure": "Structure & Rhythm"
                },
                "corrections": "Suggested Improvements",
                "synonyms": "Synonyms & Elegance",
                "getSynonyms": "Enrich Vocabulary",
                "apply": "Apply",
                "empty": "Write at least 50 characters to launch pedagogical analysis.",
                "strength": "Text Strength"
            }
        },
        "library": {
            "title": "AI Library",
            "subtitle": "Unlimited Knowledge",
            "desc": "Access millions of educational resources.",
            "searchPlaceholder": "Subject, author, book, question...",
            "searchBtn": "Explore",
            "searching": "Searching...",
            "analyzing": "Smart Analysis",
            "freeBooks": "Free Books (livre21.com)",
            "localBooks": "My Local Collection",
            "privateCollection": "My Private Collection",
            "hide": "Hide",
            "download": "Download",
            "open": "Open",
            "read": "Read",
            "readOnline": "Read Online",
            "downloadKeep": "Download & Keep",
            "keep": "Keep",
            "startRead": "Read Now",
            "summarize": "Summarize",
            "flashcards": "Flashcards",
            "quiz": "AI Quiz",
            "deleteConfirm": "Delete this book?",
            "summaryTitle": "AI Summary",
            "keyPoints": "Key Takeaways",
            "readingTime": "Reading Time",
            "difficulty": "Difficulty",
            "glossary": "Glossary",
            "createQuiz": "Create Quiz",
            "createFlashcards": "Flashcards",
            "loadingSummary": "Gemini is synthesizing knowledge...",
            "readerTitle": "LEVELMAK Integrated Reader",
            "clear": "Clear",
            "reco": "AI Reco",
            "sources": "Open Access Sources (Humanitarian)",
            "emptySearch": "No results found.",
            "geminiSearch": "Gemini is exploring databases...",
            "geminiAnalyze": "Analyzing educational resources..."
        },
        "shop": {
            "title": "LEVELMAK Shop",
            "subtitle": "Equip your Avatar",
            "desc": "Spend your hard-earned LevelCoins to customize your profile and show off your achievements to the community.",
            "balance": "Balance",
            "items": "Items",
            "tabs": {
                "all": "All",
                "avatar": "Avatars",
                "badge": "Badges",
                "theme": "Themes",
                "potion": "Potions"
            },
            "success": "Purchase successful: ",
            "owned": "Owned",
            "stock": "Stock",
            "active": "Active",
            "equip": "Equip",
            "buy": "Buy",
            "use": "Use",
            "empty": "No items found in this category.",
            "insufficient": "Not enough LevelCoins! 🪙"
        },
        "items": {
            "potion_double_xp": {
                "name": "Double XP Potion",
                "desc": "Doubles your XP gains for 5 minutes."
            },
            "potion_shield": {
                "name": "Quiz Shield",
                "desc": "Forgives one wrong answer during a quiz."
            },
            "potion_skip": {
                "name": "Rescue Vial",
                "desc": "Allows skimming a quiz question without answering."
            },
            "potion_inspiration": {
                "name": "Essence of Inspiration",
                "desc": "Gives a unique novel idea via AI."
            },
            "potion_mystery": {
                "name": "Mystery Vial",
                "desc": "Unlocks a random avatar in the shop."
            },
            "potion_fortune": {
                "name": "Elixir of Fortune",
                "desc": "Increases LevelCoins gains for 10 minutes."
            },
            "badge_elite": {
                "name": "Elite Badge",
                "desc": "Shows off your exceptional student status."
            },
            "badge_master": {
                "name": "Quiz Master",
                "desc": "For those who never miss a question."
            },
            "theme_gold": {
                "name": "Royal Gold Theme",
                "desc": "A luxurious interface for your dashboard."
            },
            "theme_neon": {
                "name": "Neon Cyber Theme",
                "desc": "A futuristic and dynamic look."
            }
        },
        "quiz": {
            "generator": {
                "title": "Generator",
                "subtitle": "Ultra-Smart",
                "desc": "Turn your courses (Photos, PDF, Word) into",
                "active": "active learning experiences",
                "badge": "Advanced Pedagogical AI",
                "uploadBtn": "Documents",
                "textBtn": "Type Text",
                "placeholder": "Paste your course here...",
                "uploadDesc": "Combine your notebook photos, PDF or Word files.",
                "generateBtn": "Launch Quiz",
                "intensity": "Intensity",
                "difficulties": {
                    "easy": "Easy",
                    "medium": "Intermediate",
                    "hard": "Expert"
                },
                "errors": {
                    "noFile": "Add at least one document or photo!",
                    "noText": "Enter text to generate the quiz!"
                },
                "status": {
                    "init": "Initializing...",
                    "prep": "Preparing documents...",
                    "read": "Reading",
                    "process": "Processing",
                    "analyze": "Pedagogical AI Analysis...",
                    "ready": "Quiz ready! Redirecting..."
                }
            },
            "player": {
                "oracle": {
                    "title": "The Prediction Oracle",
                    "subtitle": "Bet on your performance to triple your coins!",
                    "betAmount": "How much do you bet?",
                    "betTarget": "Your score goal?",
                    "startBtn": "Start Quiz",
                    "none": "None"
                },
                "potions": {
                    "shield": "Activate Shield",
                    "skip": "Use Rescue"
                },
                "feedback": {
                    "success": [
                        "Awesome!",
                        "Bravo!",
                        "You are a genius!",
                        "What mastery!",
                        "Exactly!"
                    ],
                    "shield": "Shield activated! Your mistake is forgiven. Try again! 🛡️",
                    "fail": "Close! Learn from this mistake.",
                    "skip": "Rescue Vial used! Moving to next question. ✨"
                },
                "results": {
                    "title": "Academic Achievement Unlocked!",
                    "completed": "You finished:",
                    "score": "Final Score",
                    "precision": "Accuracy",
                    "xp": "XP Gained",
                    "time": "Time",
                    "betWin": "Prediction Validated!",
                    "betFail": "Prediction Failed",
                    "betWinMsg": "Congratulations! You won",
                    "betFailMsg": "Too bad! The goal of",
                    "summary": "Course Summary",
                    "summarySub": "Smart synthesis generated by AI",
                    "keyPoints": "Key Points",
                    "lexicon": "Technical Lexicon",
                    "retryBtn": "Retry Quiz",
                    "downloadBtn": "Download Sheet (PDF)",
                    "homeBtn": "Back to Dashboard"
                }
            }
        },
        "ranking": {
            "title": "Global Ranking",
            "subtitle": "LEVELMAK's elite in real time",
            "refresh": "Refresh",
            "refreshing": "Refreshing...",
            "calculating": "Calculating global ranks...",
            "allChallengers": "All Challengers",
            "top50": "World Top 50",
            "me": "Me",
            "level": "Level",
            "totalXp": "TOTAL XP",
            "noPlayers": "No other players found.",
            "disclaimer": "The ranking is updated every 24 hours by TMAB GROUP. Keep taking quizzes to climb the leaderboard!"
        },
        "flashcards": {
            "memorization": "Fast Memorization",
            "aiSubtitle": "AI transforms your courses into active memorization cards to learn 3x faster.",
            "searchPlaceholder": "Search for a deck...",
            "aiPrompt": "What do you want to memorize today?",
            "subjectPlaceholder": "Flashcards subject...",
            "generate": "Generate",
            "myDecks": "My Decks",
            "cards": "cards",
            "studiedYesterday": "Studied yesterday",
            "neverStudied": "Never studied",
            "launch": "Launch",
            "deleteConfirm": "Do you really want to delete this flashcard deck?",
            "emptyState": "No decks for the moment. Use the AI generator above to start!",
            "createdDeck": "New Deck Created",
            "createdDeckDesc": "A deck of {count} flashcards on \"{title}\" has been generated."
        },
        "planner": {
            "strategic": "Strategic Planner",
            "successScheduled": "Your Success Scheduled",
            "subtitle": "Let the AI organize your revisions smartly to maximize retention and minimize stress.",
            "examDate": "Exam Date",
            "subjectsToReview": "Subjects to review",
            "subjectPlaceholder": "Ex: Math, Science...",
            "add": "Add",
            "docsAndPhotos": "Documents & Photos (Optional)",
            "aiAnalysisDesc": "AI will analyze your real courses (Photos, PDF, Word) for a tailored program.",
            "generatePlan": "Generate my plan",
            "generating": "Generating...",
            "start": "Start",
            "end": "End",
            "topicsIdentified": "Identified Topics",
            "redoPlan": "Redo a plan",
            "timeline": "My Revision Timeline",
            "duration": "duration",
            "aiTips": "AI Tips",
            "focusTitle": "Focus & Productivity",
            "focusDesc": "Concentrate on subjects where you have the most difficulty in the morning, when your brain is fresh. 🧠⚡",
            "pomodoroTitle": "Pomodoro Technique",
            "pomodoroDesc": "Work in sessions of 25 minutes followed by a 5-minute break to maintain maximum concentration. ⏲️✅",
            "moreTips": "More tips",
            "errorQuota": "⏳ API Quotas reached. Wait 1-2 minutes and try again!",
            "errorFail": "Generation failed. Try again!",
            "tooltip": {
                "fillDateAndSubject": "Fill exam date and add at least one subject",
                "selectDate": "Select an exam date",
                "addSubject": "Add at least one subject by clicking +",
                "generatePlan": "Click to generate your plan!"
            },
            "validation": {
                "selectDateAndSubject": "Select a date and at least one subject!",
                "clickToAdd": "Click the + button to add \"{title}\""
            }
        },
        "onboarding": {
            "welcome": "Welcome to LEVELMAK",
            "start": "Start Adventure",
            "skip": "Skip Intro",
            "next": "Next"
        },
        "levelBot": {
            "sessions": "My Discussions",
            "newChat": "New Discussion",
            "deleteConfirm": "Delete this discussion?",
            "empty": "No active discussions.",
            "back": "Back to chat"
        }
    },
    "ar": {
        "common": {
            "loading": "جار التحميل...",
            "save": "حفظ",
            "cancel": "إلغاء",
            "delete": "حذف",
            "edit": "تعديل",
            "close": "يغلق",
            "back": "رجوع",
            "next": "التالي",
            "finish": "إنهاء",
            "error": "حدث خطأ",
            "success": "نجاح",
            "search": "بحث...",
            "filter": "تصفية",
            "autoGenerated": "توليد تلقائي",
            "date": "التاريخ",
            "exportPDF": "تصدير بصيغة PDF",
            "exporting": "جاري التصدير..."
        },
        "auth": {
            "login": "تسجيل الدخول",
            "register": "إنشاء حساب",
            "logout": "تسجيل الخروج",
            "guest": "المتابعة كضيف",
            "joinElite": "انضم إلى النخبة",
            "championReturn": "عودة البطل",
            "claimThrone": "استعد عرشك",
            "identityVerif": "التحقق من الهوية",
            "accessAuthorized": "تم التصريح بالدخول",
            "pseudoOrEmail": "اسم المستخدم أو البريد الإلكتروني",
            "pseudo": "اسم المستخدم الخاص بك",
            "email": "البريد الإلكتروني الشخصي",
            "password": "كلمة المرور",
            "newPassword": "كلمة مرور جديدة (6 أحرف على الأقل)",
            "gender": "الجنس",
            "ageRange": "الفئة العمرية",
            "age1518": "15-18 سنة",
            "age1923": "19-23 سنة",
            "age24plus": "24+ سنة",
            "acceptPolicy": "أوافق على سياسات الخصوصية لـ LEVELMAK",
            "forgot": "نسيت كلمة المرور؟",
            "backToLogin": "العودة لتسجيل الدخول",
            "backToPrev": "العودة للخطوة السابقة",
            "verifyIdentity": "التحقق من الهوية",
            "changeAccess": "تغيير الوصول",
            "verifying": "جاري التحقق...",
            "requestValidated": "تم التحقق من الطلب!",
            "updatingAccess": "مجموعة TMAB تقوم بتحديث وصول النخبة الخاص بك...",
            "errorSystem": "النظام: خطأ",
            "orVia": "أو عبر",
            "googleAuth": "المصادقة عبر جوجل",
            "biometricAuth": "تسجيل دخول بيومتري",
            "accessDashboard": "الدخول إلى لوحة القيادة",
            "continue": "متابعة",
            "propelKnowledge": "دفع معرفتي للأمام",
            "legal": "متوافق مع حماية البيانات • وصول آمن عبر SSL",
            "placeholderPseudo": "مثال: mouctar1234",
            "placeholderEmail": "مثال: mail@ecole.com"
        },
        "nav": {
            "dashboard": "لوحة القيادة",
            "quiz": "اختبار الذكاء الاصطناعي",
            "summary": "ملخص الذكاء الاصطناعي",
            "library": "المكتبة",
            "writing": "ورشة الكتابة",
            "flashcards": "البطاقات التعليمية",
            "ranking": "الترتيب",
            "shop": "المتجر",
            "planner": "مخطط الذكاء الاصطناعي",
            "social": "المجتمع",
            "settings": "الإعدادات",
            "ailab": "مختبر الذكاء الاصطناعي",
            "feedback": "الآراء",
            "rating": "تقييم التطبيق"
        },
        "settings": {
            "title": "الإعدادات",
            "subtitle": "النظام",
            "desc": "خصص تجربتك في LEVELMAK وقم بإدارة معلوماتك الشخصية.",
            "panel": "لوحة التحكم",
            "profile": "الملف الشخصي والهوية",
            "appearance": "المظهر",
            "notifications": "الإشعارات",
            "security": "الأمان",
            "photoTitle": "صورة الملف الشخصي",
            "photoDesc": "تنسيق JPG أو PNG أو GIF. الحد الأقصى 5 ميجابايت.",
            "fullName": "الاسم الكامل",
            "phoneNum": "رقم الهاتف",
            "saveBtn": "حفظ التغييرات",
            "saving": "جار الحفظ...",
            "success": "تم حفظ التغييرات!",
            "darkMode": "الوضع الداكن",
            "darkOn": "نشط افتراضيًا",
            "lightOn": "الوضع الفاتح نشط",
            "appSounds": "أصوات التطبيق",
            "soundsOn": "تفعيل التأثيرات",
            "soundsOff": "الأصوات معطلة",
            "fontSize": "حجم الخط",
            "fontSizeDesc": "اضبط حجم النص لراحتك.",
            "lang": "اللغة",
            "currentLang": "العربية (AR)",
            "version": "الإصدار",
            "build": "v2.4.0",
            "notifTitle": "تفضيلات الإشعارات",
            "notifDesc": "اختر كيف تريد أن تبقى على اطلاع.",
            "notifMissions": "تذكيرات المهام",
            "notifQuiz": "اختبارات ذكية جديدة",
            "notifCommunity": "تنبيهات المجتمع",
            "securityTitle": "حماية الحساب",
            "securityDesc": "إدارة أمان الوصول الخاص بك.",
            "changePw": "تغيير كلمة المرور",
            "oldPw": "كلمة المرور القديمة",
            "newPw": "كلمة المرور الجديدة",
            "sessions": "الجلسات النشطة",
            "sessionsDesc": "أنت متصل على هذا الجهاز (تطبيق الجوال)."
        },
        "layout": {
            "important": "مهم",
            "welcome": "مرحباً،",
            "ready": "مستعد لجلسة التعلم؟",
            "me": "أنا",
            "infoAvatarTitle": "الصورة الشخصية والهوية",
            "infoAvatarQ": "📸 كيف تغير صورتك؟",
            "infoAvatarDesc": "في LEVELMAK، صورتك الشخصية هي رتبتك. لا يمكنك تحميل صورة خارجية: لتُحترم في الترتيب، يجب عليك **شراء صورك الرمزية من المتجر** بالعملات المعدنية الخاصة بك. كلما كانت صورتك أندر، كان وضعك النخبوي غير قابل للنقاش!",
            "infoRulesTitle": "القواعد الذهبية",
            "infoRule1": "الاحترام المتبادل: المجتمع قائم على المساعدة المتبادلة.",
            "infoRule2": "النزاهة: اربح نقاط الخبرة (XP) دون غش لتتقدم بصدق.",
            "infoRule3": "السرية: بياناتك محمية بواسطة مجموعة TMAB.",
            "infoQualityTitle": "التزام الجودة من مجموعة TMAB",
            "infoQualityDesc": "نحن ملتزمون بالنضال من أجل إبقاء LEVELMAK الأداة الأكثر سهولة وقوة وابتكاراً للشباب الأفريقي والعالمي. المستقبل لمن يتعلم.",
            "infoGotIt": "فهمت، لننطلق!",
            "bubblePatience": "الصبر... 🧘‍♂️",
            "bubblePatienceDesc": "{min} دقيقة إضافية من العمل لفتح الاسترخاء.",
            "installIosTitle": "التثبيت على الآيفون",
            "installIosDesc": "أضف LEVELMAK إلى شاشتك الرئيسية للحصول على تجربة مثالية ووصول سريع.",
            "installIosStep1": "انقر على زر **المشاركة** في أسفل سفاري.",
            "installIosStep2": "مرر لأسفل واضغط على **الإضافة إلى الشاشة الرئيسية**.",
            "installIosStep3": "انقر على **إضافة** في أعلى اليمين.",
            "installIosGotIt": "مفهوم!",
            "installApp": "تثبيت التطبيق",
            "installBtn": "تثبيت التطبيق",
            "elitePortal": "بوابة النخبة",
            "eliteStudent": "طالب محترف",
            "logout": "تسجيل خروج"
        },
        "dashboard": {
            "online": "متصل",
            "offline": "غير متصل",
            "time": {
                "min": "دقيقة",
                "hoursShort": "س",
                "minShort": "د"
            },
            "stats": {
                "xp": "إجمالي XP",
                "quiz": "الاختبارات المنجزة",
                "time": "وقت الدراسة",
                "badges": "الأوسمة"
            },
            "profile": {
                "level": "المستوى",
                "studentPro": "طالب PRO",
                "eliteMember": "عضو نخبة",
                "nextLevel": "أنت في",
                "ofNextLevel": "من المستوى التالي",
                "remaining": "متبقي"
            },
            "dice": {
                "chance": "الحظ اليومي",
                "title": "نرد الحظ",
                "subtitle": "انقر لتجربة حظك! 🎁✨",
                "rolling": "جار الرمي...",
                "won": "فاز",
                "item": "ملحق نادر للغاية!",
                "itemDesc": "تحقق من مخزونك في المتجر!",
                "joker": "جوكر فاز!",
                "jokerDesc": "لقد تلقيت قنينة إنقاذ!",
                "jackpot": "الجائزة الكبرى !!!",
                "preparing": "المدرب يجهز المفاجأة...",
                "modalTitle": "نرد الحظ",
                "modalSubtitle": "ارم النرد واكتشف جائزتك!",
                "spin": "رمي النرد",
                "itemWon": "إكسسوار نادر جداً!",
                "checkInventory": "تحقق من مخزونك في المتجر!",
                "jokerWon": "ربحت جوكر!",
                "jokerMsg": "لقد حصلت على قارورة إنقاذ!",
                "coachPreparing": "المدرب يجهز المفاجأة...",
                "accessory": "إكسسوار"
            },
            "motivation": {
                "title": "روح اليوم",
                "loading": "الإلهام قيد التقدم...",
                "author": "مدرب الذكاء الاصطناعي"
            },
            "vocab": {
                "title": "اكتشاف اليوم",
                "subtitle": "أثر مفرداتك",
                "example": "مثال"
            },
            "activity": {
                "title": "النشاط الأخير",
                "viewAll": "عرض الكل",
                "reduce": "تصغير",
                "empty": "لا يوجد نشاط."
            },
            "missions": {
                "title": "الأهداف",
                "empty": "تم إكمال جميع الأهداف! 🎉"
            },
            "ranking": {
                "title": "التصنيف",
                "button": "التصنيف العالمي"
            },
            "footer": {
                "property": "ملكية حصرية لـ"
            },
            "srs": {
                "title": "للمراجعة",
                "items": "عناصر مستحقة",
                "cardsDue": "بطاقات للمراجعة"
            }
        },
        "creativeWriting": {
            "title": "اكتب قصتك",
            "tag": "المساحة الإبداعية",
            "newDraft": "مسودة جديدة",
            "tabs": {
                "write": "كتابة",
                "myStories": "كتاباتي",
                "discover": "اكتشف"
            },
            "categories": {
                "story": "قصة",
                "poem": "قصيدة",
                "column": "مقال عمودي",
                "essay": "مقال",
                "other": "أخرى"
            },
            "form": {
                "titleLabel": "عنوان العمل",
                "titlePlaceholder": "مثال: لغز شجرة الباوباب الضخمة...",
                "contentLabel": "نصك",
                "contentPlaceholder": "كان يا ما كان في قرية بعيدة...",
                "characters": "حرف",
                "public": "عام",
                "saveBtn": "حفظ",
                "saving": "جاري الحفظ...",
                "documentSettings": "إعدادات المستند"
            },
            "coach": {
                "title": "مدرب الذكاء الاصطناعي",
                "subtitle": "إلهام وتحليل",
                "reviewBtn": "رأي",
                "helpBtn": "ساعدني",
                "potion": "جوهرا الإلهام",
                "empty": "انقر على \"ساعدني\" لأكتب البقية، أو على \"رأي\" للحصول على تحليلي.",
                "analysis": "تحليل المدرب",
                "suggestion": "اقتراح إبداعي",
                "insert": "إدراج في النص",
                "errorQuota": "عذراً! المدرب متعب قليلاً (تم الوصول إلى الحصة). حاول مرة أخرى بعد دقيقة!",
                "errorGeneral": "واجه المدرب مشكلة صغيرة. حاول مرة أخرى."
            },
            "list": {
                "empty": "اكتب تحفتك الأولى",
                "startBtn": "ابدأ الكتابة",
                "deleteConfirm": "هل أنت متأكد أنك تريد حذف هذا العمل؟",
                "modified": "تعديل",
                "by": "بواسطة"
            },
            "writingLab": {
                "title": "مساعد مختبر الكتابة",
                "analyzeBtn": "إطلاق التحليل المتميز",
                "analyzing": "جاري التحليل...",
                "score": "درجة الكتابة",
                "criteria": {
                    "style": "الأسلوب والطلاقة",
                    "grammar": "القواعد والإملاء",
                    "vocabulary": "الثراء اللغوي",
                    "structure": "البنية والإيقاع"
                },
                "corrections": "التحسينات المقترحة",
                "synonyms": "المترادفات والأناقة",
                "getSynonyms": "إثراء المفردات",
                "apply": "تطبيق",
                "empty": "اكتب 50 حرفًا على الأقل لإطلاق التحليل التربوي.",
                "strength": "قوة النص"
            }
        },
        "library": {
            "title": "مكتبة الذكاء الاصطناعي",
            "subtitle": "معرفة غير محدودة",
            "desc": "الوصول إلى ملايين الموارد التعليمية.",
            "searchPlaceholder": "موضوع، مؤلف، كتاب، سؤال...",
            "searchBtn": "استكشاف",
            "searching": "بحث...",
            "analyzing": "تحليل ذكي",
            "freeBooks": "كتب مجانية (livre21.com)",
            "localBooks": "مجموعتي المحلية",
            "privateCollection": "مجموعتي الخاصة",
            "hide": "إخفاء",
            "download": "تحميل",
            "open": "فتح",
            "read": "قراءة",
            "readOnline": "قراءة عبر الإنترنت",
            "downloadKeep": "تحميل وحفظ",
            "keep": "حفظ",
            "startRead": "اقرأ الآن",
            "summarize": "تلخيص",
            "flashcards": "بطاقات تعليمية",
            "quiz": "اختبار ذكي",
            "deleteConfirm": "حذف هذا الكتاب؟",
            "summaryTitle": "ملخص الذكاء الاصطناعي",
            "keyPoints": "النقاط الرئيسية",
            "readingTime": "وقت القراءة",
            "difficulty": "الصعوبة",
            "glossary": "المصطلحات",
            "createQuiz": "إنشاء اختبار",
            "createFlashcards": "بطاقات تعليمية",
            "loadingSummary": "Gemini يقوم بتلخيص المعرفة...",
            "readerTitle": "قارئ LEVELMAK المدمج",
            "clear": "مسح",
            "reco": "توصية الذكاء الاصطناعي",
            "sources": "مصادر الوصول الحر (الإنسانية)",
            "emptySearch": "لم يتم العثور على نتائج.",
            "geminiSearch": "Gemini يستكشف قواعد البيانات...",
            "geminiAnalyze": "تحليل الموارد التعليمية..."
        },
        "shop": {
            "title": "متجر LEVELMAK",
            "subtitle": "جهز الأفاتار الخاص بك",
            "desc": "أنفق عملات LevelCoins التي كسبتها بشق الأنفس لتخصيص ملفك الشخصي وعرض إنجازاتك للمجتمع.",
            "balance": "الرصيد",
            "items": "العناصر",
            "tabs": {
                "all": "الكل",
                "avatar": "أفاتار",
                "badge": "شارات",
                "theme": "سمات",
                "potion": "جرعات"
            },
            "success": "تم الشراء بنجاح: ",
            "owned": "مملوك",
            "stock": "مخزون",
            "active": "نشط",
            "equip": "تجهيز",
            "buy": "شراء",
            "use": "استخدام",
            "empty": "لا توجد عناصر في هذه الفئة.",
            "insufficient": "لا توجد عملات LevelCoins كافية! 🪙"
        },
        "items": {
            "potion_double_xp": {
                "name": "جرعة XP مضاعفة",
                "desc": "تضاعف مكاسب XP لمدة 5 دقائق."
            },
            "potion_shield": {
                "name": "درع الاختبار",
                "desc": "يغفر إجابة خاطئة واحدة أثناء الاختبار."
            },
            "potion_skip": {
                "name": "قارورة الإنقاذ",
                "desc": "تسمح بتخطي سؤال اختبار دون إجابة."
            },
            "potion_inspiration": {
                "name": "جوهر الإلهام",
                "desc": "يعطي فكرة رواية فريدة عبر الذكاء الاصطناعي."
            },
            "potion_mystery": {
                "name": "قارورة غامضة",
                "desc": "تفتح أفاتار عشوائي في المتجر."
            },
            "potion_fortune": {
                "name": "إكسير الحظ",
                "desc": "يزيد مكاسب LevelCoins لمدة 10 دقائق."
            },
            "badge_elite": {
                "name": "شارة النخبة",
                "desc": "تظهر حالة الطالب الاستثنائية الخاصة بك."
            },
            "badge_master": {
                "name": "سيد الاختبارات",
                "desc": "لأولئك الذين لا يخطئون أبداً في أي سؤال."
            },
            "theme_gold": {
                "name": "نسق الذهب الملكي",
                "desc": "واجهة فاخرة للوحة القيادة الخاصة بك."
            },
            "theme_neon": {
                "name": "نسق نيون سايبر",
                "desc": "مظهر مستقبلي وديناميكي."
            }
        },
        "quiz": {
            "generator": {
                "title": "المولد",
                "subtitle": "فائق الذكاء",
                "desc": "حول دروسك (صور، PDF، Word) إلى تجارب تعلم",
                "active": "نشطة",
                "badge": "الذكاء الاصطناعي التربوي المتقدم",
                "uploadBtn": "مستندات",
                "textBtn": "إدخال نص",
                "placeholder": "الصق درسك هنا...",
                "uploadDesc": "اجمع صور دفاتر الملاحظات أو ملفات PDF أو Word.",
                "generateBtn": "إطلاق الاختبار",
                "intensity": "الشدة",
                "difficulties": {
                    "easy": "سهل",
                    "medium": "متوسط",
                    "hard": "خبير"
                },
                "errors": {
                    "noFile": "أضف مستندًا أو صورة واحدة على الأقل!",
                    "noText": "أدخل نصًا لإنشاء الاختبار!"
                },
                "status": {
                    "init": "جار التهيئة...",
                    "prep": "جار إعداد المستندات...",
                    "read": "قراءة",
                    "process": "معالجة",
                    "analyze": "تحليل الذكاء الاصطناعي التربوي...",
                    "ready": "الاختبار جاهز! جاري إعادة التوجيه..."
                }
            },
            "player": {
                "oracle": {
                    "title": "عراب التوقعات",
                    "subtitle": "راهن على أدائك لمضاعفة عملاتك ثلاث مرات!",
                    "betAmount": "كم تراهن؟",
                    "betTarget": "هدفك في النتيجة؟",
                    "startBtn": "بدء الاختبار",
                    "none": "لا شيء"
                },
                "potions": {
                    "shield": "تفعيل الدرع",
                    "skip": "استخدام الإنقاذ"
                },
                "feedback": {
                    "success": [
                        "رائع!",
                        "برافو!",
                        "أنت عبقري!",
                        "يا له من إتقان!",
                        "بالضبط!"
                    ],
                    "shield": "تم تفعيل الدرع! خطأك مغفور. حاول مرة أخرى! 🛡️",
                    "fail": "قريب! تعلم من هذا الخطأ.",
                    "skip": "تم استخدام قنينة الإنقاذ! الانتقال إلى السؤال التالي. ✨"
                },
                "results": {
                    "title": "تم تحقيق إنجاز أكاديمي!",
                    "completed": "لقد أنهيت:",
                    "score": "النتيجة النهائية",
                    "precision": "الدقة",
                    "xp": "XP المكتسبة",
                    "time": "الوقت",
                    "betWin": "تم التحقق من التوقع!",
                    "betFail": "فشل التوقع",
                    "betWinMsg": "مبروك! لقد ربحت",
                    "betFailMsg": "للأسف! لم يتم تحقيق هدف",
                    "summary": "ملخص الدورة",
                    "summarySub": "توليف ذكي تم إنشاؤه بواسطة الذكاء الاصطناعي",
                    "keyPoints": "النقاط الرئيسية",
                    "lexicon": "المعجم التقني",
                    "retryBtn": "إعادة الاختبار",
                    "downloadBtn": "تنزيل الورقة (PDF)",
                    "homeBtn": "العودة إلى لوحة التحكم"
                }
            }
        },
        "ranking": {
            "title": "التصنيف العالمي",
            "subtitle": "نخبة LEVELMAK في الوقت الفعلي",
            "refresh": "تحديث",
            "refreshing": "جارٍ التحديث...",
            "calculating": "جارٍ حساب الرتب العالمية...",
            "allChallengers": "جميع المتحدين",
            "top50": "أفضل 50 في العالم",
            "me": "أنا",
            "level": "مستوى",
            "totalXp": "إجمالي XP",
            "noPlayers": "لم يتم العثور على لاعبين آخرين.",
            "disclaimer": "يتم تحديث الترتيب كل 24 ساعة بواسطة TMAB GROUP. استمر في حل الاختبارات لتسلق جدول الترتيب!"
        },
        "flashcards": {
            "memorization": "حفظ سريع",
            "aiSubtitle": "يحول الذكاء الاصطناعي دروسك إلى بطاقات حفظ نشطة للتعلم بشكل أسرع بـ 3 مرات.",
            "searchPlaceholder": "ابحث عن مجموعة...",
            "aiPrompt": "ماذا تريد أن تحفظ اليوم؟",
            "subjectPlaceholder": "موضوع البطاقات التعليمية...",
            "generate": "توليد",
            "myDecks": "مجموعاتي",
            "cards": "بطاقات",
            "studiedYesterday": "تمت المذاكرة بالأمس",
            "neverStudied": "لم تتم المذاكرة أبداً",
            "launch": "إطلاق",
            "deleteConfirm": "هل تريد حقًا حذف مجموعة البطاقات التعليمية هذه؟",
            "emptyState": "لا توجد مجموعات في الوقت الحالي. استخدم مولد الذكاء الاصطناعي أعلاه للبدء!",
            "createdDeck": "تم إنشاء مجموعة جديدة",
            "createdDeckDesc": "تم إنشاء مجموعة من {count} بطاقات تعليمية حول \"{title}\"."
        },
        "planner": {
            "strategic": "مخطط استراتيجي",
            "successScheduled": "نجاحك المبرمج",
            "subtitle": "دع الذكاء الاصطناعي ينظم مراجعاتك بذكاء لزيادة الاستبقاء وتقليل التوتر.",
            "examDate": "تاريخ الامتحان",
            "subjectsToReview": "المواد المراد مراجعتها",
            "subjectPlaceholder": "مثال: رياضيات، علوم...",
            "add": "إضافة",
            "docsAndPhotos": "المستندات والصور (اختياري)",
            "aiAnalysisDesc": "سيحلل الذكاء الاصطناعي دروسك الحقيقية (صور، PDF، Word) لبرنامج مخصص.",
            "generatePlan": "إنشاء خطتي",
            "generating": "جارٍ الإنشاء...",
            "start": "البداية",
            "end": "النهاية",
            "topicsIdentified": "الموضوعات المحدد",
            "redoPlan": "إعادة إنشاء خطة",
            "timeline": "جدول المراجعة الخاص بي",
            "duration": "المدة",
            "aiTips": "نصائح الذكاء الاصطناعي",
            "focusTitle": "التركيز والإنتاجية",
            "focusDesc": "ركز على المواد التي تجد فيها أكبر قدر من الصعوبة في الصباح، عندما يكون عقلك نشطاً. 🧠⚡",
            "pomodoroTitle": "تقنية بومودورو",
            "pomodoroDesc": "اعمل في جلسات مدتها 25 دقيقة تليها استراحة لمدة 5 دقائق للحفاظ على أقصى قدر من التركيز. ⏲️✅",
            "moreTips": "المزيد من النصائح",
            "errorQuota": "⏳ تم الوصول إلى حصص API. انتظر 1-2 دقيقة وحاول مرة أخرى!",
            "errorFail": "فشل الإنشاء. حاول مرة أخرى!",
            "tooltip": {
                "fillDateAndSubject": "املأ تاريخ الامتحان وأضف مادة واحدة على الأقل",
                "selectDate": "اختر تاريخ الامتحان",
                "addSubject": "أضف مادة واحدة على الأقل بالنقر فوق +",
                "generatePlan": "انقر لإنشاء خطتك!"
            },
            "validation": {
                "selectDateAndSubject": "اختر تاريخاً ومادة واحدة على الأقل!",
                "clickToAdd": "انقر فوق الزر + لإضافة \"{title}\""
            }
        },
        "onboarding": {
            "welcome": "مرحبا بكم في LEVELMAK",
            "start": "ابدأ المغامرة",
            "skip": "تخطى المقدمة",
            "next": "التالي"
        },
        "levelBot": {
            "sessions": "محادثاتي",
            "newChat": "محادثة جديدة",
            "deleteConfirm": "حذف هذه المحادثة؟",
            "empty": "لا توجد محادثات نشطة.",
            "back": "العودة للمحادثة"
        }
    }
};
