
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Plus,
    Search,
    Sparkles,
    BookOpen,
    Clock,
    ChevronRight,
    Zap,
    Trash2,
    Brain,
    Loader2,
    Calendar,
    Layers,
    Download,
    CheckCircle2
} from 'lucide-react';
import { useStore } from '../hooks/useStore';
import { geminiService } from '../services/gemini';
import { FlashcardDeck, Flashcard } from '../types';
import { logUserActivity } from '../services/activityService';

interface FlashcardsProps {
    onStartSession: (deck: FlashcardDeck, cards: Flashcard[]) => void;
}

const Flashcards: React.FC<FlashcardsProps> = ({ onStartSession }) => {
    const { user, decks, flashcards, saveFlashcardDeck, deleteFlashcardDeck, addActivity, downloadCourse, offlinePacks, t, settings } = useStore();
    const [searchQuery, setSearchQuery] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatorInput, setGeneratorInput] = useState('');

    const handleGenerateDeck = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!generatorInput.trim()) return;

        setIsGenerating(true);
        try {
            const cards = await geminiService.generateFlashcards(generatorInput, generatorInput, settings.language);

            const newDeck: FlashcardDeck = {
                id: `deck_${Date.now()}`,
                title: generatorInput.length > 30 ? generatorInput.substring(0, 30) + '...' : generatorInput,
                subject: t('common.autoGenerated') || 'IA',
                cardCount: cards.length,
                createdAt: new Date().toISOString()
            };

            // Associate cards with the new deck
            const cardsWithDeckId: Flashcard[] = cards.map(c => ({
                ...c,
                deckId: newDeck.id,
                interval: 0,
                easeFactor: 2.5,
                repetitions: 0
            }));

            saveFlashcardDeck(newDeck, cardsWithDeckId);
            addActivity('study', t('flashcards.createdDeck'), t('flashcards.createdDeckDesc').replace('{count}', cards.length.toString()).replace('{title}', newDeck.title));
            if (user) {
                logUserActivity(user.id, user.name, 'creative', `Created Flashcard Deck: ${newDeck.title}`, { count: cards.length, subject: generatorInput });
            }
            setGeneratorInput('');
        } catch (error) {
            console.error("Failed to generate deck", error);
        } finally {
            setIsGenerating(false);
        }
    };

    const filteredDecks = decks.filter(deck =>
        deck.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        deck.subject.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="max-w-6xl mx-auto py-4 md:py-8 px-4 space-y-8 md:space-y-12 animate-fade-in">
            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 border-b border-white/5 pb-10">
                <div className="space-y-3 md:space-y-4">
                    <div className="flex items-center gap-2 md:gap-3 text-primary-light font-black uppercase tracking-[0.2em] text-[8px] md:text-xs">
                        <Zap size={12} md:size={16} /> {t('flashcards.memorization')}
                    </div>
                    <h1 className="text-2xl md:text-5xl font-display font-black text-white tracking-tighter">Flashcards <span className="text-gradient-primary">IA</span></h1>
                    <p className="text-slate-400 text-base md:text-lg font-medium max-w-xl">{t('flashcards.aiSubtitle')}</p>
                </div>

                <div className="flex gap-4">
                    <div className="relative group">
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500 group-focus-within:text-primary transition-colors" size={20} />
                        <input
                            type="text"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder={t('flashcards.searchPlaceholder')}
                            className="bg-white/5 border border-white/10 rounded-2xl pl-12 pr-6 py-4 outline-none focus:border-primary/50 text-white font-bold transition-all w-full md:w-64"
                        />
                    </div>
                </div>
            </div>

            {/* AI Generator Box */}
            <div className="relative group">
                <div className="absolute -inset-1 bg-gradient-to-r from-primary/30 to-secondary/30 rounded-[2.5rem] blur opacity-75 group-hover:opacity-100 transition-opacity"></div>
                <div className="relative glass p-5 md:p-8 rounded-[1.5rem] md:rounded-[2.5rem] border border-white/10 overflow-hidden">
                    <div className="flex flex-col lg:flex-row items-center gap-6 md:gap-8">
                        <div className="flex-1 space-y-4 md:space-y-6 w-full">
                            <div className="inline-flex items-center gap-2 px-3 md:px-4 py-1.5 md:py-2 bg-primary/10 text-primary rounded-full text-[8px] md:text-xs font-black uppercase tracking-widest border border-primary/20">
                                <Sparkles size={12} md:size={14} /> Intelligence Artificielle
                            </div>
                            <h2 className="text-xl md:text-3xl font-display font-black text-white leading-tight">
                                {t('flashcards.aiPrompt').split('\n').map((line, i) => <React.Fragment key={i}>{line}<br className="hidden md:block" /></React.Fragment>)}
                            </h2>
                            <form onSubmit={handleGenerateDeck} className="relative">
                                <input
                                    type="text"
                                    value={generatorInput}
                                    onChange={(e) => setGeneratorInput(e.target.value)}
                                    placeholder={t('flashcards.subjectPlaceholder')}
                                    className="w-full p-4 md:p-5 bg-white/5 border border-white/10 rounded-xl md:rounded-2xl outline-none focus:border-primary transition-all text-white font-bold text-sm md:text-base"
                                />
                                <button
                                    type="submit"
                                    disabled={isGenerating || !generatorInput.trim()}
                                    className="absolute right-1.5 md:right-2 top-1.5 md:top-2 bottom-1.5 md:top-2 px-4 md:px-8 bg-primary hover:bg-primary-light text-white rounded-lg md:rounded-xl font-black uppercase tracking-widest text-[8px] md:text-xs transition-all shadow-glow flex items-center gap-1.5 md:gap-2 disabled:opacity-50"
                                >
                                    {isGenerating ? <Loader2 size={14} className="md:w-[18px] md:h-[18px] animate-spin" /> : <><Plus size={14} className="md:w-[18px] md:h-[18px]" /> {t('flashcards.generate')}</>}
                                </button>
                            </form>
                        </div>
                        <div className="hidden lg:block w-72 h-44 relative">
                            <div className="absolute top-0 right-0 w-40 h-56 bg-primary/20 rounded-3xl rotate-12 blur-2xl"></div>
                            <motion.div
                                animate={{ y: [0, -10, 0], rotate: [5, 2, 5] }}
                                transition={{ duration: 4, repeat: Infinity }}
                                className="absolute top-4 right-12 w-48 h-32 glass rounded-2xl border border-white/20 shadow-2xl flex items-center justify-center p-6 text-center"
                            >
                                <span className="text-white font-bold text-sm">Quelles sont les trois lois de Newton ?</span>
                            </motion.div>
                            <motion.div
                                animate={{ y: [0, 10, 0], rotate: [-5, -2, -5] }}
                                transition={{ duration: 5, repeat: Infinity, delay: 0.5 }}
                                className="absolute bottom-4 left-4 w-48 h-32 glass rounded-2xl border border-white/10 shadow-2xl flex items-center justify-center p-6 text-center"
                            >
                                <span className="text-primary-light font-black text-xs uppercase tracking-widest">Activer le Mode Elite</span>
                            </motion.div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Decks Grid */}
            <div className="space-y-8">
                <div className="flex items-center justify-between">
                    <h3 className="text-2xl font-display font-bold text-white flex items-center gap-3">
                        <div className="w-10 h-10 bg-secondary/10 text-secondary rounded-xl flex items-center justify-center border border-secondary/20">
                            <Layers size={20} />
                        </div>
                        Mes Decks ({filteredDecks.length})
                    </h3>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <AnimatePresence>
                        {filteredDecks.map((deck) => (
                            <motion.div
                                key={deck.id}
                                layout
                                initial={{ opacity: 0, scale: 0.9 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.9 }}
                                className="group cursor-pointer"
                                onClick={() => {
                                    const deckCards = flashcards.filter(c => c.deckId === deck.id);
                                    onStartSession(deck, deckCards);
                                }}
                            >
                                <div className="glass p-6 md:p-8 rounded-[1.5rem] md:rounded-[2rem] border border-white/5 shadow-xl hover:border-primary/40 transition-all relative overflow-hidden h-full flex flex-col">
                                    <div className="absolute top-0 right-0 p-4 md:p-6 opacity-5 group-hover:opacity-10 transition-opacity">
                                        <Brain size={60} md:size={80} />
                                    </div>

                                    <div className="space-y-4 md:space-y-6 relative z-10">
                                        <div className="flex justify-between items-start">
                                            <div className="px-2.5 py-1 bg-white/5 rounded-lg text-[8px] md:text-[10px] font-black uppercase tracking-widest text-slate-400">
                                                {deck.subject}
                                            </div>
                                            <div className="flex items-center gap-4">
                                                <div className="flex items-center gap-1.5 text-[10px] md:text-xs font-bold text-primary">
                                                    <Layers size={12} md:size={14} /> {deck.cardCount} {t('flashcards.cards')}
                                                </div>
                                                <button
                                                    onClick={async (e) => {
                                                        e.stopPropagation();
                                                        await downloadCourse(deck.id);
                                                    }}
                                                    className={`w-8 h-8 rounded-xl flex items-center justify-center transition-all ${offlinePacks.includes(deck.id)
                                                        ? 'bg-green-500/20 text-green-500'
                                                        : 'bg-white/5 text-slate-500 hover:bg-primary/20 hover:text-primary'
                                                        }`}
                                                    title="Télécharger pour le mode hors-ligne"
                                                >
                                                    {offlinePacks.includes(deck.id) ? <CheckCircle2 size={14} /> : <Download size={14} />}
                                                </button>
                                                <button
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        if (confirm(t('flashcards.deleteConfirm'))) {
                                                            deleteFlashcardDeck(deck.id);
                                                            addActivity('study', t('common.delete'), deck.title);
                                                        }
                                                    }}
                                                    className="w-8 h-8 rounded-xl bg-white/5 text-slate-500 hover:bg-red-500/20 hover:text-red-500 transition-all flex items-center justify-center opacity-0 group-hover:opacity-100"
                                                >
                                                    <Trash2 size={14} />
                                                </button>
                                            </div>
                                        </div>

                                        <div>
                                            <h4 className="text-lg md:text-xl font-bold text-white mb-1.5 md:mb-2 leading-tight group-hover:text-primary-light transition-colors">{deck.title}</h4>
                                            <div className="flex items-center gap-3 md:gap-4 text-[10px] md:text-xs text-slate-500 font-medium">
                                                <span className="flex items-center gap-1.5"><Clock size={10} md:size={12} /> {deck.lastStudied ? t('flashcards.studiedYesterday') : t('flashcards.neverStudied')}</span>
                                                <span className="flex items-center gap-1.5"><Calendar size={10} md:size={12} /> {new Date(deck.createdAt).toLocaleDateString()}</span>
                                            </div>
                                        </div>

                                        <div className="pt-4 md:pt-6 border-t border-white/5 mt-auto flex items-center justify-between">
                                            <span className="text-[10px] font-black uppercase tracking-widest text-primary flex items-center gap-1">
                                                {t('flashcards.launch')} <ChevronRight size={12} md:size={14} />
                                            </span>
                                            <div className="w-8 h-8 rounded-full bg-primary/10 text-primary flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all">
                                                <Zap size={16} />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </AnimatePresence>

                    {filteredDecks.length === 0 && !isGenerating && (
                        <div className="col-span-full py-20 text-center space-y-4">
                            <div className="w-20 h-20 bg-white/5 rounded-3xl flex items-center justify-center mx-auto text-slate-600">
                                <BookOpen size={40} />
                            </div>
                            <div className="space-y-1">
                                <p className="text-white font-bold text-xl">{t('flashcards.emptyState')}</p>
                            </div>
                        </div>
                    )}
                </div>

                {/* Bottom Spacer for Mobile Nav Bar Navigation Bar Compatibility */}
                <div className="h-24 md:hidden"></div>
            </div>
        </div>
    );
};

export default Flashcards;
