
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Plus,
    Search,
    Sparkles,
    BookOpen,
    Clock,
    ChevronRight,
    Zap,
    Trash2,
    Brain,
    Loader2,
    Calendar,
    Layers,
    Download,
    CheckCircle2,
    ShieldCheck,
    Camera,
    Image as ImageIcon,
    X
} from 'lucide-react';
import { useStore } from '../hooks/useStore';
import { aiService } from '../services/aiService';
import { FlashcardDeck, Flashcard } from '../types';
import { logUserActivity } from '../services/activityService';
import { useFlashcardStore } from '../services/flashcardStore';
import { FlashcardMode } from './FlashcardMode';

interface FlashcardsProps {
    onStartSession: (deck: FlashcardDeck, cards: Flashcard[]) => void;
}

const Flashcards: React.FC<FlashcardsProps> = ({ onStartSession }) => {
    const { user, decks, flashcards, saveFlashcardDeck, deleteFlashcardDeck, addActivity, downloadCourse, offlinePacks, t, settings } = useStore();
    const { cards: srsCards, getCardsToReview } = useFlashcardStore();
    const [searchQuery, setSearchQuery] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatorInput, setGeneratorInput] = useState('');
    const [selectedImage, setSelectedImage] = useState<string | null>(null);
    const [selectedSrsTopic, setSelectedSrsTopic] = useState<string | null>(null);
    const fileInputRef = React.useRef<HTMLInputElement>(null);

    if (selectedSrsTopic !== null) {
        return <FlashcardMode onClose={() => setSelectedSrsTopic(null)} filterTopic={selectedSrsTopic === 'all' ? undefined : selectedSrsTopic} />;
    }

    const reviewCount = getCardsToReview().length;

    // Group SRS cards by sourceQuizTitle
    const srsGroups = srsCards.reduce((acc, card) => {
        const title = card.sourceQuizTitle || 'Général';
        if (!acc[title]) acc[title] = [];
        acc[title].push(card);
        return acc;
    }, {} as Record<string, typeof srsCards>);

    const topicsToReview = Object.keys(srsGroups).filter(topic => 
        srsGroups[topic].some(c => c.nextReviewDate <= Date.now())
    );

    const handleGenerateDeck = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!generatorInput.trim() && !selectedImage) return;

        setIsGenerating(true);
        try {
            const sources: { type: 'text' | 'image' | 'pdf' | 'word', data: string }[] = [];
            if (generatorInput.trim()) {
                sources.push({ type: 'text', data: generatorInput });
            }
            if (selectedImage) {
                sources.push({ type: 'image', data: selectedImage });
            }

            const cards = await aiService.generateMultimodalFlashcards(sources, generatorInput || 'Nouveau Deck Photo', settings.language);

            const newDeck: FlashcardDeck = {
                id: `deck_${Date.now()}`,
                title: generatorInput.length > 30 ? generatorInput.substring(0, 30) + '...' : (generatorInput || 'Deck Photo ' + new Date().toLocaleDateString()),
                subject: t('common.autoGenerated') || 'IA',
                cardCount: cards.length,
                createdAt: new Date().toISOString()
            };

            // Associate cards with the new deck
            const cardsWithDeckId: Flashcard[] = cards.map(c => ({
                ...c,
                deckId: newDeck.id,
                interval: 0,
                easeFactor: 2.5,
                repetitions: 0
            }));

            saveFlashcardDeck(newDeck, cardsWithDeckId);
            addActivity('study', t('flashcards.createdDeck'), t('flashcards.createdDeckDesc').replace('{count}', cards.length.toString()).replace('{title}', newDeck.title));
            if (user) {
                logUserActivity(user.id, user.name, 'creative', `Created Flashcard Deck: ${newDeck.title}`, { count: cards.length, subject: generatorInput });
            }
            setGeneratorInput('');
        } catch (error) {
            console.error("Failed to generate deck", error);
            alert("Erreur lors de la génération. Veuillez réessayer. " + (error as any).message);
        } finally {
            setIsGenerating(false);
        }
    };

    const filteredDecks = decks.filter(deck =>
        deck.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        deck.subject.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="max-w-6xl mx-auto py-4 md:py-8 px-4 space-y-8 md:space-y-12 animate-fade-in">
            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 border-b border-slate-200 dark:border-white/5 pb-10">
                <div className="space-y-3 md:space-y-4">
                    <h1 className="text-2xl md:text-5xl font-display font-black text-slate-900 dark:text-white tracking-tighter">Flashcards</h1>
                    <p className="text-slate-700 dark:text-slate-300 text-base md:text-lg font-bold max-w-xl">{t('flashcards.aiSubtitle')}</p>
                </div>

                <div className="flex gap-4">
                    <div className="relative group">
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-primary transition-colors" size={20} />
                        <input
                            type="text"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder="Rechercher une leçon..."
                            className="bg-white dark:bg-white/5 border border-slate-300 dark:border-white/10 rounded-2xl pl-12 pr-6 py-4 outline-none focus:border-primary/50 text-slate-900 dark:text-white font-bold transition-all w-full md:w-64 placeholder:text-slate-400 shadow-sm"
                        />
                    </div>
                </div>
            </div>

            {/* AI Generator Box */}
            <div className="relative group">
                <div className="absolute -inset-1 bg-gradient-to-r from-primary/30 to-secondary/30 rounded-[2.5rem] blur opacity-75 group-hover:opacity-100 transition-opacity"></div>
                <div className="relative bg-white dark:bg-slate-900/80 p-5 md:p-8 rounded-[1.5rem] md:rounded-[2.5rem] border border-slate-200 dark:border-white/10 overflow-hidden shadow-xl">
                    <div className="flex flex-col lg:flex-row items-center gap-6 md:gap-8">
                        <div className="flex-1 space-y-4 md:space-y-6 w-full">
                            <h2 className="text-xl md:text-3xl font-display font-black text-slate-900 dark:text-white leading-tight">
                                {t('flashcards.aiPrompt').split('\n').map((line, i) => <React.Fragment key={i}>{line}<br className="hidden md:block" /></React.Fragment>)}
                            </h2>                             <form onSubmit={handleGenerateDeck} className="relative space-y-4">
                                {selectedImage && (
                                    <div className="flex items-center gap-4 animate-fade-in mb-2">
                                        <div className="relative">
                                            <img src={selectedImage} alt="Preview" className="h-20 w-20 object-cover rounded-xl border border-slate-300 dark:border-white/20 shadow-lg" />
                                            <button onClick={() => setSelectedImage(null)} className="absolute -top-2 -right-2 w-6 h-6 bg-slate-800 text-white rounded-full flex items-center justify-center border border-white/20 hover:bg-slate-700 shadow-xl transition-colors">
                                                <X size={12} />
                                            </button>
                                        </div>
                                        <p className="text-xs text-slate-600 dark:text-slate-400 font-bold italic">Image sélectionnée pour analyse...</p>
                                    </div>
                                )}
                                
                                <input
                                    type="file"
                                    accept="image/*"
                                    ref={fileInputRef}
                                    className="hidden"
                                    onChange={(e) => {
                                        const file = e.target.files?.[0];
                                        if (file) {
                                            const reader = new FileReader();
                                            reader.onloadend = () => {
                                                const img = new Image();
                                                img.onload = () => {
                                                    const canvas = document.createElement('canvas');
                                                    const MAX_WIDTH = 1000;
                                                    const MAX_HEIGHT = 1000;
                                                    let width = img.width;
                                                    let height = img.height;
                                                    
                                                    if (width > height) {
                                                        if (width > MAX_WIDTH) {
                                                            height *= MAX_WIDTH / width;
                                                            width = MAX_WIDTH;
                                                        }
                                                    } else {
                                                        if (height > MAX_HEIGHT) {
                                                            width *= MAX_HEIGHT / height;
                                                            height = MAX_HEIGHT;
                                                        }
                                                    }
                                                    
                                                    canvas.width = width;
                                                    canvas.height = height;
                                                    const ctx = canvas.getContext('2d');
                                                    if (ctx) {
                                                        ctx.drawImage(img, 0, 0, width, height);
                                                        setSelectedImage(canvas.toDataURL('image/jpeg', 0.8));
                                                    } else {
                                                        setSelectedImage(reader.result as string);
                                                    }
                                                };
                                                img.src = reader.result as string;
                                            };
                                            reader.readAsDataURL(file);
                                        }
                                    }}
                                />

                                <div className="flex flex-col md:flex-row gap-3 items-center">
                                    <div className="flex gap-2 shrink-0 self-start md:self-auto w-full md:w-auto">
                                        <button
                                            type="button"
                                            onClick={() => {
                                                if (fileInputRef.current) {
                                                    fileInputRef.current.setAttribute('capture', 'environment');
                                                    fileInputRef.current.click();
                                                }
                                            }}
                                            className="flex-1 md:flex-none h-12 md:h-14 bg-blue-500/10 hover:bg-blue-500/20 text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-white rounded-xl md:rounded-2xl flex items-center justify-center transition-all border border-blue-500/20"
                                            title="Prendre en photo mon cours"
                                        >
                                            <Camera className="w-5 h-5 md:w-6 md:h-6" />
                                        </button>
                                        <button
                                            type="button"
                                            onClick={() => {
                                                if (fileInputRef.current) {
                                                    fileInputRef.current.removeAttribute('capture');
                                                    fileInputRef.current.click();
                                                }
                                            }}
                                            className="flex-1 md:flex-none h-12 md:h-14 bg-slate-100 dark:bg-white/5 hover:bg-slate-200 dark:hover:bg-white/10 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white rounded-xl md:rounded-2xl flex items-center justify-center transition-all border border-slate-200 dark:border-white/5"
                                            title="Choisir une image"
                                        >
                                            <ImageIcon className="w-5 h-5 md:w-6 md:h-6" />
                                        </button>
                                    </div>
                                    <div className="flex flex-col md:flex-row flex-1 gap-3 w-full">
                                        <input
                                            type="text"
                                            value={generatorInput}
                                            onChange={(e) => setGeneratorInput(e.target.value)}
                                            placeholder={t('flashcards.subjectPlaceholder')}
                                            className="w-full p-4 md:p-5 bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl md:rounded-2xl outline-none focus:border-primary transition-all text-slate-900 dark:text-white font-bold text-sm md:text-base placeholder:text-slate-400"
                                        />
                                        <button
                                            type="submit"
                                            disabled={isGenerating || (!generatorInput.trim() && !selectedImage)}
                                            className="w-full md:w-auto py-4 md:py-0 px-4 md:px-8 bg-primary hover:bg-primary-light text-white rounded-xl font-black uppercase tracking-widest text-[10px] md:text-xs transition-all shadow-glow flex items-center justify-center gap-2 disabled:opacity-50"
                                        >
                                            {isGenerating ? <Loader2 size={16} className="md:w-[18px] md:h-[18px] animate-spin" /> : <><Plus size={16} className="md:w-[18px] md:h-[18px]" /> {t('flashcards.generate')}</>}
                                        </button>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <div className="hidden lg:block w-72 h-44 relative">
                            <div className="absolute top-0 right-0 w-40 h-56 bg-primary/20 rounded-3xl rotate-12 blur-2xl"></div>
                            <motion.div
                                animate={{ y: [0, -10, 0], rotate: [5, 2, 5] }}
                                transition={{ duration: 4, repeat: Infinity }}
                                className="absolute top-4 right-12 w-48 h-32 bg-white dark:bg-slate-900/90 rounded-2xl border border-slate-200 dark:border-white/20 shadow-2xl flex items-center justify-center p-6 text-center"
                            >
                                <span className="text-slate-900 dark:text-white font-bold text-sm">Quelles sont les trois lois de Newton ?</span>
                            </motion.div>
                            <motion.div
                                animate={{ y: [0, 10, 0], rotate: [-5, -2, -5] }}
                                transition={{ duration: 5, repeat: Infinity, delay: 0.5 }}
                                className="absolute bottom-4 left-4 w-48 h-32 bg-white dark:bg-slate-900/90 rounded-2xl border border-slate-200 dark:border-white/10 shadow-2xl flex items-center justify-center p-6 text-center"
                            >
                                <span className="text-primary dark:text-primary-light font-black text-xs uppercase tracking-widest">Activer le Mode Elite</span>
                            </motion.div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Decks Grid */}
            <div className="space-y-8">
                <div className="flex items-center justify-between">
                    <h3 className="text-2xl font-display font-bold text-slate-900 dark:text-white flex items-center gap-3">
                        <div className="w-10 h-10 bg-secondary/10 text-secondary rounded-xl flex items-center justify-center border border-secondary/20">
                            <Layers size={20} />
                        </div>
                        Mes Leçons ({filteredDecks.length + Object.keys(srsGroups).length})
                    </h3>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {/* Special SRS Decks for Quiz Errors, Grouped by Topic */}
                    <AnimatePresence>
                        {Object.keys(srsGroups).map((topic) => {
                            const topicCards = srsGroups[topic];
                            const topicReviewCount = topicCards.filter(c => c.nextReviewDate <= Date.now()).length;
                            
                            return (
                                <motion.div
                                    key={`srs_${topic}`}
                                    layout
                                    initial={{ opacity: 0, scale: 0.9 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    className="group cursor-pointer"
                                    onClick={() => setSelectedSrsTopic(topic)}
                                >
                                    <div className="glass p-6 md:p-8 rounded-[1.5rem] md:rounded-[2rem] border border-purple-500/30 shadow-xl hover:border-purple-500/50 transition-all relative overflow-hidden h-full flex flex-col bg-purple-500/5">
                                        <div className="absolute top-0 right-0 p-4 md:p-6 opacity-10 group-hover:opacity-20 transition-opacity">
                                            <Brain className="w-[60px] h-[60px] md:w-[80px] md:h-[80px] text-purple-500" />
                                        </div>

                                        <div className="space-y-4 md:space-y-6 relative z-10">
                                            <div className="flex justify-between items-start">
                                                <div className="px-2.5 py-1 bg-purple-500/20 rounded-lg text-[8px] md:text-[10px] font-black uppercase tracking-widest text-purple-400">
                                                    Mémorisation Auto
                                                </div>
                                                <div className="flex items-center gap-2">
                                                    {topicReviewCount > 0 && (
                                                        <div className="px-2 py-0.5 bg-orange-500 text-white rounded-full text-[8px] font-black animate-pulse">
                                                            {topicReviewCount} À RÉVISER
                                                        </div>
                                                    )}
                                                </div>
                                            </div>

                                            <div>
                                                <h4 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white mb-1.5 md:mb-2 leading-tight group-hover:text-purple-400 transition-colors">Erreurs : {topic}</h4>
                                                <p className="text-[10px] md:text-xs text-slate-500 font-medium leading-relaxed">
                                                    {topicCards.length} questions ratées sauvegardées pour ce sujet spécifique.
                                                </p>
                                            </div>

                                            <div className="pt-4 md:pt-6 border-t border-purple-500/10 mt-auto flex items-center justify-between">
                                                <span className="text-[10px] font-black uppercase tracking-widest text-purple-400 flex items-center gap-1">
                                                    {topicReviewCount > 0 ? "Continuer la mémorisation" : "Consulter mes cartes"} <ChevronRight className="w-3 h-3 md:w-3.5 md:h-3.5" />
                                                </span>
                                                <div className="w-8 h-8 rounded-full bg-purple-500/10 text-purple-400 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all">
                                                    <ShieldCheck size={16} />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </motion.div>
                            );
                        })}
                    </AnimatePresence>

                    <AnimatePresence>
                        {filteredDecks.map((deck) => (
                            <motion.div
                                key={deck.id}
                                layout
                                initial={{ opacity: 0, scale: 0.9 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.9 }}
                                className="group cursor-pointer"
                                onClick={() => {
                                    const rawCards = flashcards.filter(c => c.deckId === deck.id);
                                    const uniqueCards = Array.from(new Map(rawCards.map(c => [c.id || c.front, c])).values());
                                    onStartSession(deck, uniqueCards);
                                }}
                            >
                                <div className="bg-white dark:bg-slate-900/60 p-6 md:p-8 rounded-[1.5rem] md:rounded-[2rem] border border-slate-200 dark:border-white/5 shadow-xl hover:border-primary/40 transition-all relative overflow-hidden h-full flex flex-col">
                                    <div className="absolute top-0 right-0 p-4 md:p-6 opacity-5 group-hover:opacity-10 transition-opacity">
                                        <Brain className="w-[60px] h-[60px] md:w-[80px] md:h-[80px]" />
                                    </div>

                                    <div className="space-y-4 md:space-y-6 relative z-10">
                                        <div className="flex justify-between items-start">
                                            <div className="px-2.5 py-1 bg-slate-100 dark:bg-white/5 rounded-lg text-[8px] md:text-[10px] font-black uppercase tracking-widest text-slate-600 dark:text-slate-400">
                                                {deck.subject}
                                            </div>
                                            <div className="flex items-center gap-4">
                                                <div className="flex items-center gap-1.5 text-[10px] md:text-xs font-bold text-primary">
                                                    <Layers className="w-3 h-3 md:w-3.5 md:h-3.5" /> {deck.cardCount} {t('flashcards.cards')}
                                                </div>
                                                <button
                                                    onClick={async (e) => {
                                                        e.stopPropagation();
                                                        await downloadCourse(deck.id);
                                                    }}
                                                    className={`w-8 h-8 rounded-xl flex items-center justify-center transition-all ${offlinePacks.includes(deck.id)
                                                        ? 'bg-emerald-500/20 text-emerald-600 dark:text-green-500'
                                                        : 'bg-slate-100 dark:bg-white/5 text-slate-500 hover:bg-primary/20 hover:text-primary'
                                                        }`}
                                                    title="Télécharger pour le mode hors-ligne"
                                                >
                                                    {offlinePacks.includes(deck.id) ? <CheckCircle2 size={14} /> : <Download size={14} />}
                                                </button>
                                                <button
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        if (confirm(t('flashcards.deleteConfirm'))) {
                                                            deleteFlashcardDeck(deck.id);
                                                            addActivity('study', t('common.delete'), deck.title);
                                                        }
                                                    }}
                                                    className="w-8 h-8 rounded-xl bg-slate-100 dark:bg-white/5 text-slate-500 hover:bg-red-500/20 hover:text-red-500 transition-all flex items-center justify-center opacity-0 group-hover:opacity-100"
                                                >
                                                    <Trash2 size={14} />
                                                </button>
                                            </div>
                                        </div>

                                        <div>
                                            <h4 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white mb-1.5 md:mb-2 leading-tight group-hover:text-primary transition-colors">{deck.title}</h4>
                                            <div className="flex items-center gap-3 md:gap-4 text-[10px] md:text-xs text-slate-600 dark:text-slate-500 font-bold">
                                                <span className="flex items-center gap-1.5"><Clock className="w-2.5 h-2.5 md:w-3 md:h-3" /> {deck.lastStudied ? t('flashcards.studiedYesterday') : t('flashcards.neverStudied')}</span>
                                                <span className="flex items-center gap-1.5"><Calendar className="w-2.5 h-2.5 md:w-3 md:h-3" /> {new Date(deck.createdAt).toLocaleDateString()}</span>
                                            </div>
                                        </div>

                                        <div className="pt-4 md:pt-6 border-t border-slate-200 dark:border-white/5 mt-auto flex items-center justify-between">
                                            <span className="text-[10px] font-black uppercase tracking-widest text-primary flex items-center gap-1">
                                                {t('flashcards.launch')} <ChevronRight className="w-3 h-3 md:w-3.5 md:h-3.5" />
                                            </span>
                                            <div className="w-8 h-8 rounded-full bg-primary/10 text-primary flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all">
                                                <Zap size={16} />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </AnimatePresence>

                    {filteredDecks.length === 0 && !isGenerating && (
                        <div className="col-span-full py-20 text-center space-y-4">
                            <div className="w-20 h-20 bg-white/5 rounded-3xl flex items-center justify-center mx-auto text-slate-600">
                                <BookOpen size={40} />
                            </div>
                            <div className="space-y-1">
                                <p className="text-slate-900 dark:text-white font-bold text-xl">{t('flashcards.emptyState')}</p>
                            </div>
                        </div>
                    )}
                </div>

                {/* Bottom Spacer for Mobile Nav Bar Navigation Bar Compatibility */}
                <div className="h-6 md:hidden"></div>
            </div>
        </div>
    );
};

export default Flashcards;
